### ISSUE TITLE
BindableBehaviourSubject

### ISSUE THREAD

**Issue by sa-he** [GuOrg/Gu.Reactive#86]
Are you interested in a PR for my BindableBehaviourSubject? It provides a read/write property 'Value' that calls OnNext it's setter. Using it, I can create a XAML binding for the view and work with observables in the ViewModel.

https://gist.github.com/sa-he/09299684686251896c1747e27f855e34

**Comment by JohanLarsson** [comment]
Hmm, I don't see a huge need for it as the idea behind this library is to make it somewhat convenient to get observables from `INotifyPropertyyChanged` that said it is a nice class and I can merge it if you feel we should add it.

One weakness with using for example `ObserveValue()` in this lib there is always a race condition as the property may have been set again by some other thread. Normally this is not much of an issue.

Your class does not have this problem.

**Comment by sa-he** [comment]
Sorry, I was not aware the concept of this lib is one-way from INPC to RX. Unless you extend the concept I wouldn't include BindableBehaviourSubject .

**Comment by JohanLarsson** [comment]
It is not set in stone but the reason it was created was to provide convenience when using RX with INPC.
